#!/bin/bash

echo "🔧 Google Sheets API Setup Guide"
echo "=================================="
echo ""
echo "To enable Google Sheets integration, follow these steps:"
echo ""
echo "1. Go to Google Cloud Console: https://console.cloud.google.com/"
echo "2. Create a new project or select an existing one"
echo "3. Enable the Google Sheets API:"
echo "   - Go to APIs & Services > Library"
echo "   - Search for 'Google Sheets API'"
echo "   - Click on it and click 'Enable'"
echo ""
echo "4. Create a Service Account:"
echo "   - Go to APIs & Services > Credentials"
echo "   - Click 'Create Credentials' > 'Service Account'"
echo "   - Fill in the details and click 'Create'"
echo "   - Skip the optional steps and click 'Done'"
echo ""
echo "5. Generate a key for the Service Account:"
echo "   - Click on the service account you just created"
echo "   - Go to the 'Keys' tab"
echo "   - Click 'Add Key' > 'Create new key'"
echo "   - Select 'JSON' and click 'Create'"
echo "   - A JSON file will be downloaded"
echo ""
echo "6. Extract values from the JSON file and update backend/.env:"
echo "   - GOOGLE_PROJECT_ID: 'project_id' from JSON"
echo "   - GOOGLE_PRIVATE_KEY_ID: 'private_key_id' from JSON"
echo "   - GOOGLE_PRIVATE_KEY: 'private_key' from JSON (keep the quotes and \\n)"
echo "   - GOOGLE_CLIENT_EMAIL: 'client_email' from JSON"
echo "   - GOOGLE_CLIENT_ID: 'client_id' from JSON"
echo ""
echo "7. Share your Google Sheet with the service account:"
echo "   - Open your Google Sheet: https://docs.google.com/spreadsheets/d/1910n1dEO2gEY7oZpDYePw5sI2416ln4VpTeGgKOmKxE/edit"
echo "   - Click 'Share' button"
echo "   - Add the service account email (from 'client_email' in JSON) as an editor"
echo "   - Uncheck 'Notify people' and click 'Share'"
echo ""
echo "8. Restart your backend server after updating the .env file"
echo ""
echo "Note: The Google Sheet will automatically get headers when the first user registers."
echo "The sheet will contain: Name, Email, Phone, Organization, Country, State, Registration Date, User ID"
echo ""
